### ISSUE TITLE
Container that is initially empty is not animated

### ISSUE THREAD

**Issue by rcdexta** [kutlugsahin/react-smooth-dnd#10]
Thanks for this awesome library. The API is well-written and I am using it here: [react-trello](https://github.com/rcdexta/react-trello)

I have one question about drag-n-drop to containers that are initially empty. When a draggable component is dropped in the container, a new wrapper is created with the following structure, but however the `animated` class is not added, so the container does not animate to create placeholder or move existing elements. 

```html
<div class="smooth-dnd-draggable-wrapper">
...
</div>
```

In the below illustration, the blocked lane is initially an empty container, note that when draggable cards are added to it, it does not animate:

![may-06-2018 12-29-39](https://user-images.githubusercontent.com/900028/39677018-401e3bf2-5129-11e8-8aa8-053419fefed1.gif)

Let me know If I am missing something! You can check the code in the repo too if needed.

**Comment by kutlugsahin** [comment]
Hi @rcdexta ,
Thanks for letting know. I will check the issue asap and get back to you.

**Comment by kutlugsahin** [comment]
I found the problem. It should be fixed in v 0.3.7. Can you verify?

**Comment by rcdexta** [comment]
Works fine now. Thanks for the swift fix!
