### ISSUE TITLE
Context API

### ISSUE THREAD

**Issue by vititu** [kutlugsahin/react-smooth-dnd#14]
Is there a bug using the Context API? I have done an example in CodeSandBox: https://codesandbox.io/s/jz1j2row15

When moving the Draggable it starts mixing up things, even though they all have a key prop. Besides that, when using create-react-app and using the Context API, after moving around the Draggable it throws an error saying it can read the id of the element, which is being used by the key prop.

**Comment by kutlugsahin** [comment]
Hi @vititu ,
Thanks for submitting the issue with an example code. I think I know the problem here. I will commit a fix with the next version asap. I will let you know.

**Comment by kutlugsahin** [comment]
It is fixed on v0.4.8. 
see [https://codesandbox.io/s/1y25z3v7yl](https://codesandbox.io/s/1y25z3v7yl)

**Comment by vititu** [comment]
Wow, that was fast! Thanks! 😁
