### ISSUE TITLE
Pass style attributes instead of dragClass and dropClass

### ISSUE THREAD

**Issue by rcdexta** [kutlugsahin/react-smooth-dnd#20]
Is it possible to pass style attributes like `dragStyle` and `dropStyle` instead of css classnames to `dragClass` and `dropClass`. Since, we are generally moving away from packaging css or scss along with react component libraries and recommend css-in-js, would be greatly helpful to have such attributes.

**Comment by kutlugsahin** [comment]
Hi @rcdexta 
For now it is not possible setting inline style for drag and drop classes. I don't know which css in js solution you use but it should be working fine as long as is generates a class name which you can set for drag and drop classes.

**Comment by rcdexta** [comment]
yup i am using `injectGlobal` helper with styled-components to do that for now
