### ISSUE TITLE
Multiple Containers all with copy behavior

### ISSUE THREAD

**Issue by maxsalven** [kutlugsahin/react-smooth-dnd#21]
Hi,

I'd like to have multiple containers, and I want to **copy** draggables from any container to any other container. I have set them all to the same `groupName` and `behavior="copy"`, however then I can not drag from one to the other. Is this a bug?

Thanks
Max

**Comment by kutlugsahin** [comment]
Hi @maxsalven 
No this is the expected behavior since containers with copy behavior does not accept drops and its items are static. I am afraid your scenario is not supported with this library.

**Comment by maxsalven** [comment]
Thanks @kutlugsahin, it actually seems to work fine with `behaviour="copy"` and `shouldAcceptDrop={() => true}`. Perhaps since it works correctly in that scenario, it could become an 'officially supported' behavior as well?

**Comment by kutlugsahin** [comment]
Yes, indeed! I have not think of this scenario when designing the API, I am glad to hear that this is also possible. May be I can also add a section to demo page for this :) Cheers!
