### ISSUE TITLE
Typescript example

### ISSUE THREAD

**Issue by georgewritescode** [kutlugsahin/react-smooth-dnd#22]
Multi list typescript example (note I forked from someone else's example)
https://codesandbox.io/s/9jnomjoj8p

**Comment by kutlugsahin** [comment]
Hey @georgewritescode,
Thanks for the example. Maybe in the future I also publish the strong types for typescript as well.
Cheers!

**Comment by shadrech** [comment]
Typescript types created yet? Would really appreciate @kutlugsahin

**Comment by kutlugsahin** [comment]
Now in progress.

**Comment by shadrech** [comment]
Thanks👍. Any idea how long it will take? @kutlugsahin

**Comment by kutlugsahin** [comment]
@shadrech You can expect it next week, hopefully :)

**Comment by shadrech** [comment]
👍

**Comment by kutlugsahin** [comment]
Hey @georgewritescode , @shadrech,
Just published version 0.6.2.  The d.ts files are in the package.
React dependency is set to ^16.3.0 by the way.
Cheers!
