### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by tchaton** [kutlugsahin/react-smooth-dnd#28]
Hello,

Would it be possible to add a orientation in grid format, which is usually very used in website.
Horizontal and vertical are pretty limitating for modern design.

Best,
Thomas Chaton.

**Comment by kutlugsahin** [comment]
Hi,

Unfortunately orientation is limited to either vertical or horizontal. All
calculations are based on this approach and it requires huge update
codebase to make it work with wrapped grid structure. I have a plan to
rewrite the core logic to support all kinds of layouts but this won't be
coming in near versions.

Cheers,
Kutlu

**Comment by JuneScut** [comment]
Anything new? @kutlugsahin
