### ISSUE TITLE
Add custom classname to Container react component

### ISSUE THREAD

**Issue by smtrd3** [kutlugsahin/react-smooth-dnd#29]
How can I add a className to Container component? Using className prop doesn't work.

**Comment by ghost** [comment]
Did you try like this ? 

`count= {this.state.count} `

**Comment by kutlugsahin** [comment]
Container accepts style property for now. But you can put it inside another div and set it's className to have desired look.

**Comment by bebraw** [comment]
@kutlugsahin It might be even more useful to allow overriding the div (think a headless component). Then it's easier to compose to fit an existing solution.

**Comment by kutlugsahin** [comment]
Actually there is an undocumented render prop for that, see following code

```jsx
<Container render={(setRef) => (
  <div ref={setRef}>
   {...} // render draggables here
  </div>
 )} />
```

**Comment by kutlugsahin** [comment]
render prop is documented now
