### ISSUE TITLE
Could not find a declaration file for module 'react-smooth-dnd'.

### ISSUE THREAD

**Issue by rogix** [kutlugsahin/react-smooth-dnd#30]
Hi guys. When I am try to import the libary  I get this:

>  Could not find a declaration file for module 'react-smooth-dnd'.

Anyone could explain to me what problem is it and how to fix it? Thanks in advance

**Comment by kutlugsahin** [comment]
Typescript version is in progress, probably coming in next week.

**Comment by kutlugsahin** [comment]
Now, you can upgrade to version 0.6.2 for typescript support
