### ISSUE TITLE
I am trying for editor 

### ISSUE THREAD

**Issue by pravinharigaikwad** [kutlugsahin/react-smooth-dnd#35]
When I drag the element from copy behavior then dropped element should be HTML element and I have to change the content of each dropped elements and store updated content in an array of objects with drag n drop support?
Please reply?

**Comment by kutlugsahin** [comment]
Use getChildPayload property to set the data for dragged item, get this data in the onDrop callback and than you can update the array or any kind of data you have

**Comment by pravinharigaikwad** [comment]
Hello Kutlu, It's resolved actually issue was with my setState now I am able to update new content to that specific index object,
Please correct me if I am wrong or there is any standard and advance way to do this.
BTW Thank you so much for providing wonderful stuff. YOU ROCK!

**Comment by kutlugsahin** [comment]
Hey @pravingkd6 thanks!
No there is no any other special way of doing this. This is the way how it supposed to be handled.
You can see example codes in the demo.
Cheers!
