### ISSUE TITLE
Is there any way to prevent coming drag & drop if container has more than 3 draggable items?

### ISSUE THREAD

**Issue by bcano-office** [kutlugsahin/react-smooth-dnd#36]
I am implementing React drag and drop using this library and I have one problem.
I have several containers in the app and I am going to prevent coming drag & drop(though I can move existing draggable into another container) if that container has more than 3 draggables inside. 🤔 
It would be nice if I can solve this issue soon. 
Thanks. 👍

**Comment by kutlugsahin** [comment]
Yes there is!
[see docs](https://github.com/kutlugsahin/react-smooth-dnd#shouldacceptdrop)

**Comment by bcano-office** [comment]
Wow. great! thanks. I missed that function in docs.
