### ISSUE TITLE
Not able to place item at the bottom after dropping 3-4 items

### ISSUE THREAD

**Issue by pravinharigaikwad** [kutlugsahin/react-smooth-dnd#37]
I have to drag n drop 3-4 items with copy behaviour but couldn’t place the item at the bottom of the container.

**Comment by kutlugsahin** [comment]
It would be easier to understand the problem if you can share a repo demonstrating the issue you're having.

**Comment by pravinharigaikwad** [comment]
Hello Kutlu,

I had shared my code earlier with name Pravin Gaikwad,
I have applied maximum height in pixel to container with style also with CSS but didn’t get resolved,

It seems my problem is mentioned in image attached in below issue:
https://github.com/kutlugsahin/react-smooth-dnd/issues/24
Thanks

**Comment by pravinharigaikwad** [comment]
Hello Kutlu,

I have resolved this as there were height applied to container now working.
Thanks :-)
