### ISSUE TITLE
Not able to drop properly in side by side container (Attached video link)

### ISSUE THREAD

**Issue by pravinharigaikwad** [kutlugsahin/react-smooth-dnd#38]
@kutlugsahin I have two containers side by side with a width 50% as columns with the assigned array with drop accept but not able to drop properly in the container but if I move element vertically from bottom to top or top to bottom then I can drop in that container but if I move element from left to right over the row then not getting proper container area to drop.

Please refer below video link:
https://www.loom.com/share/2b7ce4a5e16e4793b8ddecbfe939c3d6

**Comment by kutlugsahin** [comment]
Hey @pravingkd6 ,
You should put a horizontal Container inside the Draggables of vertical Container. So it should look like this.

```jsx
<Container>
 <Draggable>
  <Container orientation="horizontal"> // or you can place two container side by side with behaviour="drop-zone"
    // inner draggables go here
  </Container>
 </Draggable>
 // other draggables
</Container>
```
I hope this helps

**Comment by pravinharigaikwad** [comment]
Hey @kutlu Thanks for quick reply actually inner draggables are vertically moving orientation in side by side container so need to check with drop-zone.

**Comment by pravinharigaikwad** [comment]
Hey @kutlu, drop-zone didn’t work for me.

**Comment by kutlugsahin** [comment]
I made an example for you trying a similar approach. Please have a look.
[https://codesandbox.io/s/4xk3yl8247?fontsize=14](https://codesandbox.io/s/4xk3yl8247?fontsize=14)

**Comment by pravinharigaikwad** [comment]
Hey @kutlugsahin ,
You are genius!
You gave me many other solutions to my problems and encouraged more to work with this plugin.
Many Thanks to you!!!!!!!!!!!!

**Comment by dev-assassin** [comment]
@kutlugsahin 
how can i put limited items in horizontal drag?
for example, I'd like to put only 3 items in one horizontal drag.
for others item, i'd like to put in new horizontal drag.
Between two horizontal drags, It will be available to drag and drop.
How can I implement this?
