### ISSUE TITLE
OnDragStart is not a function

### ISSUE THREAD

**Issue by Samuel-Montoya** [kutlugsahin/react-smooth-dnd#4]
**Uncaught TypeError: t.getOptions.onDragStart is not a function
    at S (index.js:1)
    at index.js:1
    at f (index.js:1)
    at HTMLDocument.a (index.js:1)**

Here is the code: 
```
<Container
    onDrop={dropResult => this.child.current.moveChart(dropResult)}
    onDragStart={this.onDragStart}>
    <LayoutContentsComponent ref={this.child} selectedLayout={this.state.selectedLayout} 
</Container>

onDragStart = (index, payload) => {
    console.log(index, payload)
}
```

**Comment by kutlugsahin** [comment]
Hi @Samuel-Montoya, thanks for letting me know the issue
It's now fixed in the version 0.3.0.
