### ISSUE TITLE
This plugin is not working in IE(Internet Explorer 11), Is there any hack for this?

### ISSUE THREAD

**Issue by pravinharigaikwad** [kutlugsahin/react-smooth-dnd#40]
Hello @kutlugsahin,  As I am utilizing this plugin in my current project but there is an error in IE as: "Object doesn't support property or method 'assign' & Unable to get property 'dispose' of undefined or null reference"
Even it is showing blank screen.
Thanks!

**Comment by kutlugsahin** [comment]
ie11 does not support Object.assign. You can easily add polyfill for this. Check out [https://github.com/zloirock/core-js](https://github.com/zloirock/core-js)
