### ISSUE TITLE
Duplicated onDrop call

### ISSUE THREAD

**Issue by objectivecosta** [kutlugsahin/react-smooth-dnd#42]
Hello,

I've hit a condition where if I drag into another container of the same groupName, onDrop is called on two containers at once, which makes my app add the object to it. I have a video demo-ing the issue: https://cl.ly/6d371064c0e6

Did anyone ever hit this?

Thanks in advance,

- rafael

**Comment by kutlugsahin** [comment]
Hey @rafaelc0sta 
onDrop is called for every container that could accept the drop. So you have to check the addedIndex and removedIndex parameters to decide to which container the dragged item will be added. You can check the demo application code to see how it's done.
Cheers!!

**Comment by objectivecosta** [comment]
Thanks!

**Comment by GraemeF** [comment]
Is it possible to determine when all affected containers have received their `onDrop`? This would be useful to batch all the related changes so that a single backend API request can be made, for example.

**Comment by GraemeF** [comment]
I spent some time looking into this and managed to get something working. I'm using a reducer to update a copy of the state (dispatching an action for each of the containers) and then an additional action to commit the final state when handling the last container. It's a bit of a faff but it seems to work.
