### ISSUE TITLE
Question about drop area

### ISSUE THREAD

**Issue by michshat** [kutlugsahin/react-smooth-dnd#5]
Thank you for this library. It's very easy to get started and getting it working. Question I have though  - if there is a way to highlight the drop area. For instance when moving a card from column to column - having be able to highlight the column when card is moved over it.

**Comment by kutlugsahin** [comment]
@michshat 
If you want to highlight the column which is a Container you can. Just handle the onDragEnter onDragLeave functions to add any css class. But if you want the highlight the final drop area of the card, it is not possible with the current design.
