### ISSUE TITLE
Incorrect position of Dragabble on drag start if parents have "transform: translate.." css property

### ISSUE THREAD

**Issue by egorzekov** [kutlugsahin/react-smooth-dnd#56]
Steps to reproduce:
1. Open demo page https://kutlugsahin.github.io/smooth-dnd-demo/.
2. Find `<div class="content">`.
3. Add inline styles `transform: translateY(0);` or any `transform: translate..`. Please note that the position of the layout is the same.
4. Start dragging any item.

Actual result:
Draggable jumps right on the distance of the right sidebar.

Expected result:
Draggable appears to be right update cursor when dragging starts.

I would like to use your great library in my project, but I can't due to this issue.

The issue doesn't reproduce with other DND libraries, so I assume that it should be easy to deal with.

**Comment by kutlugsahin** [comment]
Hey @egorzekov. 
Please check this property. [https://github.com/kutlugsahin/react-smooth-dnd#getghostparent](https://github.com/kutlugsahin/react-smooth-dnd#getghostparent)
set Container _getGhostParent_ property to some function that returns document body. That will create the ghost as a child of the body and wont be affected by transformed element.
