### ISSUE TITLE
Can't drop on another Container

### ISSUE THREAD

**Issue by BennievanderWel** [kutlugsahin/react-smooth-dnd#7]
When I have:

    class WidgetDrawer extends React.Component {
    
      onDrop() {
         console.log('Dropped on drawer!')
      }
    
      render() {
    
        const items = [{ id: 1, name: 'Widget A'}, { id: 2, name: 'Widget B'}];
    
        return (
          <div>
            <Container onDrop={this.onDrop}>
              {items.map(item => {
                return (
                  <Draggable key={item.id}>
                    {item.name}
                  </Draggable>
                );
              })}
            </Container>
                
            <Container style={{ backgroundColor: 'yellow', height: 100, width: 100 }} onDrop={() => console.log(5)}>
    
            </Container>
          </div>
        );
      }
    }
    
    export default WidgetDrawer;

and I drop an item from the first Container on the second, the console.log() is never triggered.

Any suggestions?

I'm on version 3.6 with React 16.2

**Comment by kutlugsahin** [comment]
Hi @BennievanderWel! You should set groupName props of the containers to the same value to accept drop from each other. You can also set shouldAcceptDrop prop for advanced scenarios. See the **[api](https://github.com/kutlugsahin/react-smooth-dnd#api)** for more information.

**Comment by BennievanderWel** [comment]
Ah, thats it. Sorry, missed it in the API. Thanks!
