### ISSUE TITLE
Is it possible to create drag/swap items w/o having items affected?

### ISSUE THREAD

**Issue by footballdaddy** [kutlugsahin/react-smooth-dnd#9]
I am trying to create a grid like swap feature. 
Moving c -> a [a,b,c,d] result: [c,b,a,d]  
Here what I hope to accomplish But it use html5 draggable. 
https://codesandbox.io/s/github/bother7/my-homepage-app

**Comment by kutlugsahin** [comment]
Hi @footballdaddy,
Unfortunately react-smooth-dnd does not support grid like wrapped elements. They should be listed in one axis. And its not using html 5 drag and drop internally.
